#
#
#spring.data.mongodb.uri=mongodb://localhost:27017/AIActivityDB
#
#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
#
#
#server.port=8082
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
#
#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#
#kafka.topic.name=activity-events
#
#
#spring.data.redis.host=localhost
#spring.data.redis.port=6380
#spring.cache.type=redis
#spring.cache.redis.key-prefix=activity-service::
#spring.cache.redis.time-to-live=600000
#

server.port=8082

spring.data.mongodb.uri=mongodb://mongo:27017/${MONGO_DB_ACTIVITY}

eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

kafka.topic.name=activity-events

spring.data.redis.host=redis
spring.data.redis.port=6379

spring.cache.type=redis
spring.cache.redis.key-prefix=activity-service::
spring.cache.redis.time-to-live=600000

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
